#!/usr/bin/env bash

files='/root/atlas-shell/loops_conditions_and_parsing/*'

for file in $files; do
    if [[ -f $file && $file =~ ^[0-9] ]]; then
        echo "File $file starts with a number"
        # Add your additional logic here
    fi
done
