#!/usr/bin/env bash
#Sit back and relax while I tell you the story of passwd

while IFS=: read -r username pass _  gid uidi home command
do
echo "The user $username is part of the $gid gang, lives in $home and rides $command. $username's place is protected by the passcode $pass, more info about the user here: $uidi"
done < /etc/passwd
