#!/usr/bin/env bash
#this loop is like the others but changes at 4 and 8

i=1

until [ $i -gt 10 ]
do
if [ $i -eq 4 ]; then
echo 'bad luck' 
elif [ $i -eq 8 ]; then
echo 'good luck' 
else
echo 'Best School'
fi
((i++))
done
