#!/usr/bin/env bash
#this is a nested loop displaying time for 12hrs 59 minutes

hours=1
echo "Hour: 0"
while [ $hours -le 13 ]; do
minutes=1
while [ $minutes -lt 60 ]; do 
echo "$minutes"
((minutes++))
done 
if [ $hours -ne 13 ]; then
echo "Hour: $hours"
fi
((hours++))
done
