#!/usr/bin/env bash
#Find file school, if it exists give info on it

file=school

if [ ! -e $file ]; then
echo "$file file does not exist"
else
echo "$file file exists"
if [ -s $file ]; then
echo "$file file is not empty"
else
echo "$file file is empty"
fi
if [ -f $file ]; then
echo "$file is a regular file"
fi
fi

